### ISSUE TITLE
I failed to build docker-compose 

### ISSUE THREAD

**Issue by franklili3** [blockchain-certificates/cert-viewer#32]
I use WIN 10,  I want to practise cert-viewer project. 
After I installed Docker and clone, I failed to build docker-compose. The error is "/cert-viewer/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning." 
 I installed python 3.5.2 and urllib3[secure]. In the python, when I import urllib3.contrib.pyopenssl, the error is " Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\frankliliwin10\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\contrib\pyopenssl.py", line 49, in <module>
    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
ImportError: No module named 'ndg'"
I  build docker-compose again, the last error is make again.
How can I do?

**Comment by kimdhamilton** [comment]
Please try with the v2 docker compose file I checked in. If that doesn't work, I recommend looking at Docker support (details in #33)
