### ISSUE TITLE
Error on python install .

### ISSUE THREAD

**Issue by karask** [blockchain-certificates/cert-viewer#47]
After latest commit (a58c9b8516b6897ecca84182e23b5dd5e337ed8b) I get the following error:

...
    building '_yaml' extension
    creating build/temp.linux-x86_64-3.5/ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/kostas/crypto/blockcerts/py3venv/include -I/usr/include/python3.5m -c ext/_yaml.c -o build/temp.linux-x86_64-3.5/ext/_yaml.o
    ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/kostas/crypto/blockcerts/py3venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ps9e7fjw/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-q_wcu19x-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/kostas/crypto/blockcerts/py3venv/include/site/python3.5/PyYAML" failed with error code 1 in /tmp/pip-build-ps9e7fjw/PyYAML/

Not certain what changed to cause this... and ideas?

Thanks

**Comment by kimdhamilton** [comment]
## Short answer: 
Can you sync to this branch and see if it clears up?
https://github.com/blockchain-certificates/cert-viewer/pull/48

## Long answer:

I tried 2 things:
- setup virtualenv with python 3.5, synced to latest commit, run `pip install .` -> no error
- setup virtualenv with python 3.5, synced to previous commit, run `pip install .`, then sync to latest commit, run `pip install .` -> no error

Based on web searches, I think you're running Ubuntu. Searching for this error message, I saw lots of hits related to Ubuntu with certain packages. So I looked to see if any of the new packages in requirements.txt can cause this (directly or transitively). Although actually, this is still relevant even if you're not running Ubuntu.

One possible solution I saw is having [python, but not python-dev installed](http://stackoverflow.com/questions/36067018/install-docker-cloud-client-using-pip
 stackoverflow.com)

Still, I wonder if a change in requirements would have made this necessary. I removed the requirements in the attached PR and verified. I'm curious if this removes the error.

**Comment by karask** [comment]
After installing python3-dev the problem was solved!

Maybe that should also go in:
https://github.com/blockchain-certificates/developer-common-docs/blob/master/virtualenv.md   ?

Thank you!
